import { createContext, useContext, useState, type ReactNode } from 'react';

export type Language = 'de' | 'ru' | 'uz' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.courses': 'Kurse',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.ausbildung': 'Ausbildung & Arbeit',
    'nav.studium': 'Studium & Ausbildung',

    // Hero
    'hero.badge': 'Sprachschule Berliner',
    'hero.title': 'Lernen Sie Deutsch',
    'hero.passion': 'mit Leidenschaft',
    'hero.subtitle': 'Ihr Weg nach Deutschland beginnt hier in Urganch. Professionelle Deutschkurse von A1 bis C2.',
    'hero.cta': 'Kurse entdecken',
    'hero.feature1': 'Goethe Prüfungszentrum',
    'hero.feature1.sub': 'Offizielle Prüfungen direkt bei uns',
    'hero.feature2': 'Moderne Ausstattung',
    'hero.feature2.sub': 'Technik, Materialien & moderne Räume',
    'hero.feature3': 'Qualifizierte Lehrer',
    'hero.feature3.sub': 'Modernste Methoden nach Goethe-Standards',
    'hero.feature4': 'Intensivkurse',
    'hero.feature4.sub': '5 Tage die Woche für maximalen Erfolg',
    'hero.contactBtn': 'Kontaktieren Sie uns',

    // Courses
    'courses.title': 'Unsere Kurse',
    'courses.subtitle': 'Ihr Weg nach Deutschland beginnt hier',
    'courses.germanA1C2': 'Deutsch A1-C2',
    'courses.germanA1C2.desc': 'Alle Niveaustufen von A1 bis C2. Unterricht 5 Tage die Woche – Intensität für Ihren maximalen Erfolg.',
    'courses.ausbildung': 'Studium und Ausbildung',
    'courses.ausbildung.desc': 'Vorbereitung und Vermittlung für Studium, Ausbildung und Arbeit in Deutschland',
    'courses.testdaf': 'TestDaF Vorbereitung',
    'courses.testdaf.desc': 'Intensive Vorbereitung fürs Studium in Deutschland',
    'courses.kids': 'Kinderkurse',
    'courses.kids.desc': 'Spielerisch Deutsch lernen für Kinder',
    'courses.level': 'Alle Niveaus',
    'courses.duration': 'Wöchentlich',
    'courses.cta.learn': 'Mehr erfahren',
    'courses.cta.contact': 'Anfragen',

    // About
    'about.hero.line1': 'Unsere',
    'about.hero.line2': 'Philosophie',
    'about.hero.quote': 'Berliner Sprachschule – nicht nur Sprachunterricht, sondern Ihr erster und zuverlässigster Schritt nach Deutschland.',
    'about.overlay.title': 'In Urganch',
    'about.overlay.text': 'Wir bringen deutsche Sprachqualität ins Herz von Xorazm.',
    'about.why.title': 'Nima uchun Berliner?',
    'about.card.intensity': 'Intensiver Unterricht',
    'about.card.intensity.text': 'Höchste Qualitätsstandards und 5 Tage die Woche intensives Lernen für maximalen Erfolg.',
    'about.card.goethe.status': 'Offizielles Prüfungszentrum',
    'about.card.goethe.status.text': 'Legen Sie Ihre Goethe-Prüfungen direkt bei uns in der Schule ab – ohne weite Wege.',
    'about.card.global': 'Globaler Standard',
    'about.card.global.text': 'Unser Unterricht basiert auf internationalen Goethe-Institut Methoden. Bei uns gibt es Ergebnisse.',
    'about.card.teachers': 'Hochqualifizierte Lehrkräfte',
    'about.card.teachers.text': 'Unsere Lehrkräfte absolvieren regelmäßig Fortbildungen nach den Standards des Goethe-Instituts.',
    'about.card.help': 'Lernen mit Spaß',
    'about.card.help.text': 'Bei uns ist Deutsch lernen nie langweilig – mit Spielen, interaktiven Materialien und kreativen Methoden.',
    'about.why.global.title': 'Globaler Standard',
    'about.why.global.text': 'Unser Unterricht basiert auf internationalen Goethe-Institut Methoden. Bei uns gibt es kein "einfach nur lernen", bei uns gibt es Ergebnisse.',
    'about.why.teachers.title': 'Erfahrene Lehrer',
    'about.why.teachers.text': 'Unsere Lehrer kennen nicht nur die Sprache, sondern haben auch die deutsche Kultur und Visaprozesse aus erster Hand erlebt.',
    'about.why.help.title': 'Echte Hilfe',
    'about.why.help.text': 'Wir unterrichten nicht nur, wir helfen unseren Schülern bei der Vorbereitung auf Visa-Interviews und beim Finden ihres Platzes in Deutschland.',
    'about.callout.line1': 'Ihr Erfolg ist',
    'about.callout.line2': 'unser',
    'about.callout.accent': 'Hauptziel',
    'about.callout.quote': 'Wir nutzen modernste Technologien, um jede Unterrichtsstunde spannend und nützlich zu gestalten.',
    'about.callout.cta': 'Kontakt aufnehmen',
    'about.values.title.line1': 'Unsere',
    'about.values.title.line2': 'Werte',
    'about.values.1.title': 'Qualität an erster Stelle',
    'about.values.1.text': 'Wir arbeiten nach den bewährten Methoden des Goethe-Instituts und garantieren höchste Unterrichtsqualität für Ihren Erfolg.',
    'about.values.2.title': 'Deutsche Atmosphäre',
    'about.values.2.text': 'Fühlen Sie sich wie auf den Straßen Berlins, während Sie in Urganch sind.',

    // Ausbildung Page
    'ausbildung.title': 'Studium, Ausbildung und Arbeit in Deutschland',
    'ausbildung.subtitle': 'Ihr kompletter Wegweiser von Urganch nach Deutschland',
    'ausbildung.process.title': 'Wie alles abläuft',
    'ausbildung.process.step1.title': 'Sprachliche Vorbereitung',
    'ausbildung.process.step1.desc': 'Intensive Deutschkurse von A1 bis B2/C1, um die sprachlichen Voraussetzungen zu erfüllen.',
    'ausbildung.process.step2.title': 'Beratung & Orientierung',
    'ausbildung.process.step2.desc': 'Wir helfen Ihnen, das passende Studium oder die richtige Ausbildung in Deutschland zu finden.',
    'ausbildung.process.step3.title': 'Bewerbungsservice',
    'ausbildung.process.step3.desc': 'Professionelle Unterstützung bei der Erstellung von Lebensläufen und Motivationsschreiben.',
    'ausbildung.process.step4.title': 'Visum & Integration',
    'ausbildung.process.step4.desc': 'Begleitung beim Visumsprozess und Vorbereitung auf das Leben in Deutschland.',
    'ausbildung.help.title': 'Beratung und Hilfe bei Bewerbung',
    'ausbildung.help.desc': 'Abgesehen von den sprachlichen Elementen unterstützen wir Sie bei der gesamten Bürokratie und den Bewerbungsprozessen bei deutschen Arbeitgebern und Universitäten.',

    // Studium Page
    'studium.badge': 'Ihr Weg nach Deutschland',
    'studium.hero.title': 'Studium, Ausbildung & Arbeit',
    'studium.hero.accent': 'in Deutschland',
    'studium.hero.subtitle': 'Wir begleiten Sie von der ersten Deutschstunde bis zu Ihrem Start in Deutschland. Professionelle Beratung und Unterstützung für Ihren Erfolg.',
    'studium.hero.cta': 'Jetzt beraten lassen',
    'studium.pathways.title': 'Wählen Sie Ihren Weg',
    'studium.pathways.subtitle': 'Drei Wege führen nach Deutschland – wir unterstützen Sie bei jedem',
    'studium.pathway.studium.title': 'Studium',
    'studium.pathway.studium.desc': 'Bachelor- und Masterstudium an deutschen Universitäten und Hochschulen',
    'studium.pathway.studium.feature1': 'Bewerbungshilfe für Universitäten',
    'studium.pathway.studium.feature2': 'Sprachkurse bis C2 Niveau',
    'studium.pathway.studium.feature3': 'Visa-Unterstützung',
    'studium.pathway.ausbildung.title': 'Ausbildung',
    'studium.pathway.ausbildung.desc': 'Duale Berufsausbildung mit Vergütung in deutschen Unternehmen',
    'studium.pathway.ausbildung.feature1': 'Vermittlung zu Arbeitgebern',
    'studium.pathway.ausbildung.feature2': 'Vorbereitung auf Interviews',
    'studium.pathway.ausbildung.feature3': 'Begleitung bis zum Vertrag',
    'studium.pathway.arbeit.title': 'Fachkraft',
    'studium.pathway.arbeit.desc': 'Arbeiten als Fachkraft mit anerkannter Qualifikation in Deutschland',
    'studium.pathway.arbeit.feature1': 'Anerkennung von Qualifikationen',
    'studium.pathway.arbeit.feature2': 'Stellenvermittlung',
    'studium.pathway.arbeit.feature3': 'Integrationshilfe',
    'studium.process.title': 'Der Weg nach Deutschland',
    'studium.process.subtitle': 'In vier Schritten zu Ihrem Ziel',
    'studium.step1.title': 'Deutsch lernen',
    'studium.step1.desc': 'Intensive Sprachkurse von A1 bis zum erforderlichen Niveau',
    'studium.step2.title': 'Dokumente vorbereiten',
    'studium.step2.desc': 'Wir helfen bei Lebenslauf, Motivationsschreiben und Anträgen',
    'studium.step3.title': 'Beratung & Vermittlung',
    'studium.step3.desc': 'Persönliche Beratung und Kontakt zu Universitäten/Arbeitgebern',
    'studium.step4.title': 'Visum & Start',
    'studium.step4.desc': 'Unterstützung beim Visum und Vorbereitung auf das Leben in Deutschland',
    'studium.benefits.title': 'Warum mit uns?',
    'studium.benefits.subtitle': 'Über 500 erfolgreiche Absolventen sind bereits in Deutschland – werden Sie Teil dieser Erfolgsgeschichte.',
    'studium.benefit1.title': 'Kostenlose Bildung',
    'studium.benefit1.desc': 'Deutsche Universitäten erheben keine Studiengebühren',
    'studium.benefit2.title': 'Anerkannte Abschlüsse',
    'studium.benefit2.desc': 'Deutsche Qualifikationen weltweit geschätzt',
    'studium.benefit3.title': 'Bezahlte Ausbildung',
    'studium.benefit3.desc': 'Verdienen Sie während der Ausbildung',
    'studium.benefit4.title': 'Hohe Lebensqualität',
    'studium.benefit4.desc': 'Sicherheit, Gesundheit und Karrieremöglichkeiten',
    'studium.benefits.cta': 'Kostenlose Beratung',
    'studium.stats.students': 'Absolventen',
    'studium.stats.success': 'Erfolgsquote',
    'studium.stats.years': 'Jahre Erfahrung',
    'studium.cta.title': 'Bereit für Ihren Weg nach Deutschland?',
    'studium.cta.subtitle': 'Vereinbaren Sie noch heute ein kostenloses Beratungsgespräch und machen Sie den ersten Schritt.',
    'studium.cta.button': 'Jetzt Termin vereinbaren',

    // Contact
    'contact.hero.title': 'Ihre Fragen',
    'contact.hero.accent': 'beantworten wir gerne',
    'contact.hero.subtitle': 'Erfahren Sie mehr über unsere Kurse, Preise und Möglichkeiten nach Deutschland zu gehen. Schreiben Sie uns einfach oder besuchen Sie uns.',
    'contact.course.a1c2.badge': 'Deutschkurse A1-C2',
    'contact.course.a1c2.title': 'Interesse an Deutschkursen?',
    'contact.course.a1c2.desc': 'Kontaktieren Sie uns für Informationen zu aktuellen Kursplänen, Preisen und verfügbaren Plätzen. Wir beraten Sie gerne!',
    'contact.course.testdaf.badge': 'TestDaF Vorbereitung',
    'contact.course.testdaf.title': 'TestDaF Prüfungsvorbereitung',
    'contact.course.testdaf.desc': 'Erfahren Sie mehr über unsere TestDaF-Vorbereitungskurse, Prüfungstermine und wie wir Sie auf die Prüfung vorbereiten.',
    'contact.course.kids.badge': 'Kinderkurse',
    'contact.course.kids.title': 'Deutschkurse für Kinder',
    'contact.course.kids.desc': 'Fragen Sie nach unseren spielerischen Kinderkursen, Altersgruppen, Zeiten und Preisen.',
    'contact.course.studium.badge': 'Studium & Ausbildung',
    'contact.course.studium.title': 'Weg nach Deutschland',
    'contact.course.studium.desc': 'Lassen Sie sich zu Studium, Ausbildung oder Arbeit in Deutschland beraten. Wir helfen Ihnen bei allen Schritten.',
    'contact.phone.label': 'Rufen Sie uns an',
    'contact.telegram.label': 'Schnelle Antwort',
    'contact.telegram.title': 'Schreiben Sie uns auf Telegram',
    'contact.instagram.label': 'Unser Alltag',
    'contact.address': 'Adresse',
    'contact.hours.label': 'Öffnungszeiten',
    'contact.hours.days': 'Montag — Samstag',

    // Footer
    'footer.rights': 'Alle Rechte vorbehalten',
    'footer.tagline': 'Ihre Deutschsprachschule in Urganch',
    'footer.social': 'Soziale Netzwerke',

    // Testimonials
    'testimonials.title': 'Bewertungen unserer Schüler',
    'testimonials.subtitle': 'Erfahren Sie, was unsere Schüler über uns sagen',

    // Header utility
    'header.search': 'Suche',
    'header.search.placeholder': 'Suche...',
    'header.myBerliner': 'Mein Berliner',
    'header.login': 'Anmelden',
    'header.register': 'Registrieren',

    // News
    'news.title': 'Neuigkeiten',
    'news.subtitle': 'Aktuelle Nachrichten aus unserer Sprachschule',
    'news.readMore': 'Weiterlesen',
    'city.name': 'Urgentsch',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.courses': 'Курсы',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.ausbildung': 'Аусбильдунг и работа',
    'nav.studium': 'Учёба и Аусбильдунг',

    // Hero
    'hero.badge': 'Sprachschule Berliner',
    'hero.title': 'Изучайте немецкий',
    'hero.passion': 'с увлечением',
    'hero.subtitle': 'Ваш путь в Германию начинается здесь, в Ургенче. Профессиональные курсы немецкого от A1 до C2.',
    'hero.cta': 'Наши курсы',
    'hero.feature1': 'Центр экзаменов Goethe',
    'hero.feature1.sub': 'Официальные экзамены проводятся у нас',
    'hero.feature2': 'Современное оснащение',
    'hero.feature2.sub': 'Техника, материалы и современные классы',
    'hero.feature3': 'Квалифицированные преподаватели',
    'hero.feature3.sub': 'Современные методы по стандартам Goethe',
    'hero.feature4': 'Интенсивные курсы',
    'hero.feature4.sub': '5 дней в неделю для максимального успеха',
    'hero.contactBtn': 'Связаться с нами',

    // Courses
    'courses.title': 'Наши курсы',
    'courses.subtitle': 'Ваш путь в Германию начинается здесь',
    'courses.germanA1C2': 'Немецкий A1-C2',
    'courses.germanA1C2.desc': 'Все уровни от A1 до C2. Занятия 5 дней в неделю — интенсивность для вашего максимального успеха.',
    'courses.ausbildung': 'Учёба и Аусбильдунг',
    'courses.ausbildung.desc': 'Подготовка и помощь в поиске учёбы, профессионального обучения и работы в Германии',
    'courses.testdaf': 'Подготовка к TestDaF',
    'courses.testdaf.desc': 'Интенсивная подготовка к учёбе в Германии',
    'courses.kids': 'Детские курсы',
    'courses.kids.desc': 'Немецкий для детей в игровой форме',
    'courses.level': 'Все уровни',
    'courses.duration': 'Еженедельно',
    'courses.cta.learn': 'Подробнее',
    'courses.cta.contact': 'Записаться',

    // About
    'about.hero.line1': 'Наша',
    'about.hero.line2': 'Философия',
    'about.hero.quote': 'Berliner Sprachschule – это не просто изучение языка, это ваш первый и самый надёжный шаг к Германии.',
    'about.overlay.title': 'В Ургенче',
    'about.overlay.text': 'Мы принесли качество немецкого языка в самое сердце Хорезма.',
    'about.why.title': 'Nima uchun Berliner?',
    'about.card.intensity': 'Интенсивное обучение',
    'about.card.intensity.text': 'Высочайшие стандарты качества и интенсивные занятия 5 дней в неделю для максимального успеха.',
    'about.card.goethe.status': 'Официальный экзаменационный центр',
    'about.card.goethe.status.text': 'Сдавайте экзамены Гёте-Института прямо у нас в школе – без долгих поездок.',
    'about.card.global': 'Мировой стандарт',
    'about.card.global.text': 'Наши занятия проводятся по международным методикам Goethe-Institut. У нас есть результаты.',
    'about.card.teachers': 'Высококвалифицированные преподаватели',
    'about.card.teachers.text': 'Наши преподаватели регулярно проходят повышение квалификации по стандартам Гёте-Института.',
    'about.card.help': 'Учёба с удовольствием',
    'about.card.help.text': 'У нас немецкий никогда не бывает скучным – игры, интерактивные материалы и креативные методы.',
    'about.why.global.title': 'Мировой стандарт',
    'about.why.global.text': 'Наши занятия проводятся по международным методикам Goethe-Institut. У нас нет "просто учёбы", у нас есть результаты.',
    'about.why.teachers.title': 'Опытные преподаватели',
    'about.why.teachers.text': 'Наши преподаватели знают не только язык, но и немецкую культуру и визовые процессы изнутри.',
    'about.why.help.title': 'Реальная помощь',
    'about.why.help.text': 'Мы не просто даём уроки, мы помогаем нашим ученикам подготовиться к визовым собеседованиям и найти своё место в Германии.',
    'about.callout.line1': 'Ваш успех —',
    'about.callout.line2': 'наша',
    'about.callout.accent': 'главная цель',
    'about.callout.quote': 'Мы используем новейшие технологии, чтобы сделать каждый урок увлекательным и полезным.',
    'about.callout.cta': 'Связаться с нами',
    'about.values.title.line1': 'Наши',
    'about.values.title.line2': 'принципы',
    'about.values.1.title': 'Качество на первом месте',
    'about.values.1.text': 'Мы работаем по проверенным методикам Goethe-Institut и гарантируем высочайшее качество обучения для вашего успеха.',
    'about.values.2.title': 'Немецкая атмосфера',
    'about.values.2.text': 'Почувствуйте себя на улицах Берлина, находясь в Ургенче.',

    // Ausbildung Page
    'ausbildung.title': 'Учёба, Аусбильдунг и работа в Германии',
    'ausbildung.subtitle': 'Ваш полный путеводитель из Ургенча в Германию',
    'ausbildung.process.title': 'Как всё проходит',
    'ausbildung.process.step1.title': 'Языковая подготовка',
    'ausbildung.process.step1.desc': 'Интенсивные курсы немецкого языка от A1 до B2/C1 для соответствия языковым требованиям.',
    'ausbildung.process.step2.title': 'Консультация и ориентация',
    'ausbildung.process.step2.desc': 'Мы помогаем вам найти подходящую учебу или профессиональное обучение в Германии.',
    'ausbildung.process.step3.title': 'Сервис по подаче заявок',
    'ausbildung.process.step3.desc': 'Профессиональная поддержка в составлении резюме и мотивационных писем.',
    'ausbildung.process.step4.title': 'Виза и интеграция',
    'ausbildung.process.step4.desc': 'Сопровождение в процессе получения визы и подготовка к жизни в Германии.',
    'ausbildung.help.title': 'Консультация и помощь в подаче заявки',
    'ausbildung.help.desc': 'Помимо языковых аспектов, мы поддерживаем вас во всей бюрократии и процессах подачи заявок немецким работодателям и университетам.',

    // Studium Page
    'studium.badge': 'Ваш путь в Германию',
    'studium.hero.title': 'Учёба, Аусбильдунг и работа',
    'studium.hero.accent': 'в Германии',
    'studium.hero.subtitle': 'Мы сопровождаем вас от первого урока немецкого до вашего старта в Германии. Профессиональные консультации и поддержка для вашего успеха.',
    'studium.hero.cta': 'Получить консультацию',
    'studium.pathways.title': 'Выберите свой путь',
    'studium.pathways.subtitle': 'Три пути ведут в Германию – мы поддержим вас на каждом',
    'studium.pathway.studium.title': 'Учёба',
    'studium.pathway.studium.desc': 'Бакалавриат и магистратура в немецких университетах',
    'studium.pathway.studium.feature1': 'Помощь с поступлением',
    'studium.pathway.studium.feature2': 'Языковые курсы до C2',
    'studium.pathway.studium.feature3': 'Визовая поддержка',
    'studium.pathway.ausbildung.title': 'Аусбильдунг',
    'studium.pathway.ausbildung.desc': 'Дуальное профессиональное обучение с оплатой в немецких компаниях',
    'studium.pathway.ausbildung.feature1': 'Подбор работодателей',
    'studium.pathway.ausbildung.feature2': 'Подготовка к собеседованиям',
    'studium.pathway.ausbildung.feature3': 'Сопровождение до договора',
    'studium.pathway.arbeit.title': 'Специалист',
    'studium.pathway.arbeit.desc': 'Работа специалистом с признанной квалификацией в Германии',
    'studium.pathway.arbeit.feature1': 'Признание квалификаций',
    'studium.pathway.arbeit.feature2': 'Поиск вакансий',
    'studium.pathway.arbeit.feature3': 'Помощь с интеграцией',
    'studium.process.title': 'Путь в Германию',
    'studium.process.subtitle': 'К цели за четыре шага',
    'studium.step1.title': 'Изучение немецкого',
    'studium.step1.desc': 'Интенсивные курсы от A1 до нужного уровня',
    'studium.step2.title': 'Подготовка документов',
    'studium.step2.desc': 'Помогаем с резюме, мотивационными письмами и заявками',
    'studium.step3.title': 'Консультация и подбор',
    'studium.step3.desc': 'Персональные консультации и связь с университетами/работодателями',
    'studium.step4.title': 'Виза и старт',
    'studium.step4.desc': 'Поддержка с визой и подготовка к жизни в Германии',
    'studium.benefits.title': 'Почему с нами?',
    'studium.benefits.subtitle': 'Более 500 выпускников уже в Германии – станьте частью этой истории успеха.',
    'studium.benefit1.title': 'Бесплатное образование',
    'studium.benefit1.desc': 'Немецкие университеты не берут плату за обучение',
    'studium.benefit2.title': 'Признанные дипломы',
    'studium.benefit2.desc': 'Немецкие квалификации ценятся во всём мире',
    'studium.benefit3.title': 'Оплачиваемое обучение',
    'studium.benefit3.desc': 'Зарабатывайте во время Аусбильдунга',
    'studium.benefit4.title': 'Высокое качество жизни',
    'studium.benefit4.desc': 'Безопасность, здравоохранение и карьерные возможности',
    'studium.benefits.cta': 'Бесплатная консультация',
    'studium.stats.students': 'Выпускников',
    'studium.stats.success': 'Успех',
    'studium.stats.years': 'Лет опыта',
    'studium.cta.title': 'Готовы к пути в Германию?',
    'studium.cta.subtitle': 'Запишитесь на бесплатную консультацию сегодня и сделайте первый шаг.',
    'studium.cta.button': 'Записаться на консультацию',

    // Contact
    'contact.hero.title': 'На ваши вопросы',
    'contact.hero.accent': 'мы ответим с удовольствием',
    'contact.hero.subtitle': 'Узнайте больше о наших курсах, ценах и возможностях поехать в Германию. Просто напишите нам или посетите нас.',
    'contact.course.a1c2.badge': 'Курсы немецкого A1-C2',
    'contact.course.a1c2.title': 'Интересуют курсы немецкого?',
    'contact.course.a1c2.desc': 'Свяжитесь с нами для информации о расписании, ценах и свободных местах. Мы с радостью проконсультируем вас!',
    'contact.course.testdaf.badge': 'Подготовка к TestDaF',
    'contact.course.testdaf.title': 'Подготовка к экзамену TestDaF',
    'contact.course.testdaf.desc': 'Узнайте о наших курсах подготовки к TestDaF, датах экзаменов и как мы готовим вас к экзамену.',
    'contact.course.kids.badge': 'Детские курсы',
    'contact.course.kids.title': 'Немецкий для детей',
    'contact.course.kids.desc': 'Спросите о наших игровых курсах для детей, возрастных группах, расписании и ценах.',
    'contact.course.studium.badge': 'Учёба и Аусбильдунг',
    'contact.course.studium.title': 'Путь в Германию',
    'contact.course.studium.desc': 'Получите консультацию по учёбе, Аусбильдунгу или работе в Германии. Мы помогаем на каждом этапе.',
    'contact.phone.label': 'Позвоните нам',
    'contact.telegram.label': 'Быстрый ответ',
    'contact.telegram.title': 'Напишите нам в Telegram',
    'contact.instagram.label': 'Наши будни',
    'contact.address': 'Адрес',
    'contact.hours.label': 'Часы работы',
    'contact.hours.days': 'Понедельник — Суббота',

    // Footer
    'footer.rights': 'Все права защищены',
    'footer.tagline': 'Ваша школа немецкого языка в Ургенче',
    'footer.social': 'Социальные сети',

    // Testimonials
    'testimonials.title': 'Отзывы наших учеников',
    'testimonials.subtitle': 'Узнайте, что говорят о нас наши ученики',

    // Header utility
    'header.search': 'Поиск',
    'header.search.placeholder': 'Поиск...',
    'header.myBerliner': 'Мой Берлинер',
    'header.login': 'Войти',
    'header.register': 'Регистрация',

    // News
    'news.title': 'Новости',
    'news.subtitle': 'Актуальные новости из нашей языковой школы',
    'news.readMore': 'Читать далее',
    'city.name': 'Ургенч',
  },
  uz: {
    // Navigation
    'nav.home': 'Bosh sahifa',
    'nav.courses': 'Kurslar',
    'nav.about': 'Biz haqimizda',
    'nav.contact': 'Aloqa',
    'nav.ausbildung': 'Ausbildung va ish',
    'nav.studium': 'Studium va Ausbildung',

    // Hero
    'hero.badge': 'Sprachschule Berliner',
    'hero.title': "Nemis tilini o'rganing",
    'hero.passion': 'ishtiyoq bilan',
    'hero.subtitle': "Germaniyaga yo'lingiz shu yerda, Urganchda boshlanadi. A1 dan C2 gacha professional nemis tili kurslari.",
    'hero.cta': 'Kurslarimiz bilan tanishing',
    'hero.feature1': 'Goethe imtihon markazi',
    'hero.feature1.sub': "Rasmiy imtihonlar bizda o'tkaziladi",
    'hero.feature2': 'Zamonaviy jihozlar',
    'hero.feature2.sub': "Texnika, materiallar va zamonaviy xonalar",
    'hero.feature3': "Yuqori malakali o'qituvchilar",
    'hero.feature3.sub': "Goethe standartlari bo'yicha zamonaviy usullar",
    'hero.feature4': 'Intensiv kurslar',
    'hero.feature4.sub': "Maksimal muvaffaqiyat uchun haftada 5 kun",
    'hero.contactBtn': "Biz bilan bog'laning",

    // Courses
    'courses.title': 'Bizning kurslar',
    'courses.subtitle': "Germaniyaga yo'lingiz shu yerdan boshlanadi",
    'courses.germanA1C2': 'Nemis tili A1-C2',
    'courses.germanA1C2.desc': "A1 dan C2 gacha barcha darajalar. Haftada 5 kun darslar — maksimal natija uchun intensiv ta'lim.",
    'courses.ausbildung': "O'qish va Ausbildung",
    'courses.ausbildung.desc': "Germaniyada o'qish, ta'lim va ish topishga tayyorgarlik va yordam",
    'courses.testdaf': 'TestDaF tayyorgarlik',
    'courses.testdaf.desc': "Germaniyada o'qish uchun intensiv tayyorgarlik",
    'courses.kids': 'Bolalar kurslari',
    'courses.kids.desc': "Bolalar uchun o'yin orqali nemis tili",
    'courses.level': 'Barcha darajalar',
    'courses.duration': 'Haftalik',
    'courses.cta.learn': "Batafsil o'qish",
    'courses.cta.contact': "Bog'lanish",

    // About
    'about.hero.line1': 'Bizning',
    'about.hero.line2': 'falsafamiz',
    'about.hero.quote': 'Berliner til maktabi – bu shunchaki til o\'rganish emas, bu sizning Germaniya sari tashlagan birinchi va eng ishonchli qadamingizdir.',
    'about.overlay.title': 'Urganchda',
    'about.overlay.text': 'Biz nemis tili sifatini Xorazm markaziga olib keldik.',
    'about.why.title': 'Nima uchun Berliner?',
    'about.card.intensity': 'Intensiv Darslar',
    'about.card.intensity.text': 'Eng yuqori sifat standartlari va haftasiga 5 kun intensiv ta\'lim – maksimal muvaffaqiyat uchun.',
    'about.card.goethe.status': 'Rasmiy Imtihon Markazi',
    'about.card.goethe.status.text': 'Goethe-Institut imtihonlarini bevosita bizning maktabda topshiring – uzoq yo\'l bosmasdan.',
    'about.card.global': 'Global Standart',
    'about.card.global.text': 'Darslarimiz xalqaro Goethe-Institut metodikasi asosida olib boriladi. Bizda natija bor.',
    'about.card.teachers': 'Yuqori Malakali Ustozlar',
    'about.card.teachers.text': 'Bizning o\'qituvchilarimiz Goethe-Institut standartlari bo\'yicha muntazam malaka oshirish kurslaridan o\'tishadi.',
    'about.card.help': 'Qiziqarli Darslar',
    'about.card.help.text': 'Bizda nemis tili o\'rganish hech qachon zerikarli emas – o\'yinlar, interaktiv materiallar va ijodiy usullar bilan.',
    'about.why.global.title': 'Global Standart',
    'about.why.global.text': 'Darslarimiz xalqaro Goethe-Institut metodikasi asosida olib boriladi. Bizda "shunchaki o\'qish" yo\'q, bizda natija bor.',
    'about.why.teachers.title': 'Tajribali Ustozlar',
    'about.why.teachers.text': 'Bizning o\'qituvchilarimiz nafaqat tilni bilishadi, balki Germaniya madaniyatini va viza jarayonlarini ham ichidan o\'rganishgan.',
    'about.why.help.title': 'Haqiqiy Ko\'mak',
    'about.why.help.text': 'Biz talabalarimizga faqat dars bermaymiz. Biz ularga viza suhbatiga tayyorlanishda va Germaniyada o\'z o\'rnini topishda yordam beramiz.',
    'about.callout.line1': 'Sizning muvaffaqiyatingiz',
    'about.callout.line2': 'bizning',
    'about.callout.accent': 'asosiy maqsadimiz',
    'about.callout.quote': 'Biz har bir darsni qiziqarli va foydali qilish uchun eng yangi texnologiyalardan foydalanamiz.',
    'about.callout.cta': 'Bizga qo\'shiling',
    'about.values.title.line1': 'Bizning',
    'about.values.title.line2': 'tamoyillarimiz',
    'about.values.1.title': 'Sifat birinchi o\'rinda',
    'about.values.1.text': 'Biz Goethe-Institut metodikasi asosida ishlaymiz va muvaffaqiyatingiz uchun eng yuqori sifatni kafolatlaymiz.',
    'about.values.2.title': 'Germaniya muhiti',
    'about.values.2.text': 'Urganchda turib o\'zingizni Berlin ko\'chalarida yurgandek his qilasiz.',

    // Ausbildung Page
    'ausbildung.title': "Germaniyada o'qish, Ausbildung va ish",
    'ausbildung.subtitle': "Urganchdan Germaniyagacha bo'lgan to'liq yo'riqnomangiz",
    'ausbildung.process.title': 'Jarayon qanday kechadi',
    'ausbildung.process.step1.title': 'Til tayyorgarligi',
    'ausbildung.process.step1.desc': "Til talablariga javob berish uchun A1 dan B2/C1 gacha intensiv nemis tili kurslari.",
    'ausbildung.process.step2.title': "Maslahat va yo'naltirish",
    'ausbildung.process.step2.desc': "Biz sizga Germaniyada mos keladigan o'qish yoki Ausbildungni topishda yordam beramiz.",
    'ausbildung.process.step3.title': 'Hujjat topshirish xizmati',
    'ausbildung.process.step3.desc': "Rezyume va motivatsiya xatlarini tayyorlashda professional yordam.",
    'ausbildung.process.step4.title': 'Viza va integratsiya',
    'ausbildung.process.step4.desc': "Viza olish jarayonida hamrohlik va Germaniyadagi hayotga tayyorgarlik.",
    'ausbildung.help.title': 'Hujjat topshirishda maslahat va yordam',
    'ausbildung.help.desc': "Til o'rganishdan tashqari, biz sizga barcha byurokratiya va Germaniya ish beruvchilari hamda universitetlariga hujjat topshirish jarayonlarida yordam beramiz.",

    // Studium Page
    'studium.badge': "Germaniyaga yo'lingiz",
    'studium.hero.title': "O'qish, Ausbildung va ish",
    'studium.hero.accent': 'Germaniyada',
    'studium.hero.subtitle': "Biz sizni birinchi nemis tili darsidan Germaniyada boshlanguningizgacha kuzatib boramiz. Muvaffaqiyatingiz uchun professional maslahat va yordam.",
    'studium.hero.cta': 'Maslahat olish',
    'studium.pathways.title': "O'z yo'lingizni tanlang",
    'studium.pathways.subtitle': "Uchta yo'l Germaniyaga olib boradi – biz har birida sizni qo'llab-quvvatlaymiz",
    'studium.pathway.studium.title': "O'qish",
    'studium.pathway.studium.desc': "Germaniya universitetlarida bakalavr va magistratura",
    'studium.pathway.studium.feature1': 'Universitetlarga hujjat topshirishda yordam',
    'studium.pathway.studium.feature2': 'C2 darajagacha til kurslari',
    'studium.pathway.studium.feature3': 'Viza yordami',
    'studium.pathway.ausbildung.title': 'Ausbildung',
    'studium.pathway.ausbildung.desc': "Germaniya kompaniyalarida maoshli kasb ta'limi",
    'studium.pathway.ausbildung.feature1': 'Ish beruvchilarni topish',
    'studium.pathway.ausbildung.feature2': 'Suhbatlarga tayyorgarlik',
    'studium.pathway.ausbildung.feature3': 'Shartnomaga qadar hamrohlik',
    'studium.pathway.arbeit.title': 'Mutaxassis',
    'studium.pathway.arbeit.desc': "Tan olingan malaka bilan Germaniyada ishlash",
    'studium.pathway.arbeit.feature1': 'Malakalarni tan olish',
    'studium.pathway.arbeit.feature2': 'Ish topish',
    'studium.pathway.arbeit.feature3': 'Integratsiya yordami',
    'studium.process.title': "Germaniyaga yo'l",
    'studium.process.subtitle': "To'rt qadamda maqsadga",
    'studium.step1.title': "Nemis tilini o'rganish",
    'studium.step1.desc': "A1 dan kerakli darajagacha intensiv kurslar",
    'studium.step2.title': 'Hujjatlarni tayyorlash',
    'studium.step2.desc': "Rezyume, motivatsiya xati va arizalarda yordam beramiz",
    'studium.step3.title': 'Maslahat va topish',
    'studium.step3.desc': "Shaxsiy maslahat va universitet/ish beruvchilar bilan aloqa",
    'studium.step4.title': 'Viza va boshlash',
    'studium.step4.desc': "Viza olishda yordam va Germaniyadagi hayotga tayyorgarlik",
    'studium.benefits.title': 'Nega biz bilan?',
    'studium.benefits.subtitle': "500 dan ortiq bitiruvchilar allaqachon Germaniyada – bu muvaffaqiyat tarixining bir qismi bo'ling.",
    'studium.benefit1.title': "Bepul ta'lim",
    'studium.benefit1.desc': "Germaniya universitetlari o'qish uchun pul olmaydi",
    'studium.benefit2.title': 'Tan olingan diplomlar',
    'studium.benefit2.desc': "Germaniya malakasi butun dunyoda qadrlanadi",
    'studium.benefit3.title': "Maoshli ta'lim",
    'studium.benefit3.desc': "Ausbildung davomida pul ishlang",
    'studium.benefit4.title': 'Yuqori hayot sifati',
    'studium.benefit4.desc': "Xavfsizlik, sog'liqni saqlash va karyera imkoniyatlari",
    'studium.benefits.cta': 'Bepul maslahat',
    'studium.stats.students': 'Bitiruvchilar',
    'studium.stats.success': 'Muvaffaqiyat',
    'studium.stats.years': 'Yillik tajriba',
    'studium.cta.title': "Germaniyaga yo'lga tayyor misiz?",
    'studium.cta.subtitle': "Bugun bepul maslahatlashuvga yoziling va birinchi qadamni tashlang.",
    'studium.cta.button': "Maslahatga yozilish",

    // Contact
    'contact.hero.title': 'Savollaringizga',
    'contact.hero.accent': 'javob beramiz',
    'contact.hero.subtitle': "Kurslarimiz, narxlar va Germaniyaga ketish imkoniyatlari haqida bepul ma'lumot oling. Shunchaki yozing yoki markazimizga keling.",
    'contact.course.a1c2.badge': 'Nemis tili kurslari A1-C2',
    'contact.course.a1c2.title': 'Nemis tili kurslariga qiziqyapsizmi?',
    'contact.course.a1c2.desc': "Joriy dars jadvali, narxlar va bo'sh joylar haqida ma'lumot olish uchun biz bilan bog'laning!",
    'contact.course.testdaf.badge': 'TestDaF tayyorgarlik',
    'contact.course.testdaf.title': 'TestDaF imtihoniga tayyorgarlik',
    'contact.course.testdaf.desc': "TestDaF tayyorgarlik kurslarimiz, imtihon sanalari va sizni qanday tayyorlashimiz haqida bilib oling.",
    'contact.course.kids.badge': 'Bolalar kurslari',
    'contact.course.kids.title': 'Bolalar uchun nemis tili',
    'contact.course.kids.desc': "O'yinli bolalar kurslarimiz, yosh guruhlari, vaqti va narxlari haqida so'rang.",
    'contact.course.studium.badge': "O'qish va Ausbildung",
    'contact.course.studium.title': "Germaniyaga yo'l",
    'contact.course.studium.desc': "Germaniyada o'qish, Ausbildung yoki ish haqida maslahat oling. Biz har bir qadamda yordam beramiz.",
    'contact.phone.label': 'Bizga qo\'ng\'iroq qiling',
    'contact.telegram.label': 'Tezkor javob',
    'contact.telegram.title': 'Telegram orqali yozish',
    'contact.instagram.label': 'Kundalik hayotimiz',
    'contact.address': 'Manzil',
    'contact.hours.label': 'Ish vaqti',
    'contact.hours.days': 'Dushanba — Shanba',

    // Footer
    'footer.rights': "Barcha huquqlar himoyalangan",
    'footer.tagline': 'Urganchdagi nemis tili maktabingiz',
    'footer.social': 'Ijtimoiy tarmoqlar',

    // Testimonials
    'testimonials.title': "O'quvchilarimiz fikrlari",
    'testimonials.subtitle': "O'quvchilarimiz biz haqimizda nima deyishlarini bilib oling",

    // Header utility
    'header.search': 'Qidiruv',
    'header.search.placeholder': 'Qidirish...',
    'header.myBerliner': 'Mening Berliner',
    'header.login': 'Kirish',
    'header.register': "Ro'yxatdan o'tish",

    // News
    'news.title': 'Yangiliklar',
    'news.subtitle': "Til maktabimizdan so'nggi yangiliklar",
    'news.readMore': "Ko'proq o'qish",
    'city.name': 'Urganch',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.ausbildung': 'Apprenticeship & Work',
    'nav.studium': 'Studies & Apprenticeship',

    // Hero
    'hero.badge': 'Sprachschule Berliner',
    'hero.title': 'Learn German',
    'hero.passion': 'with passion',
    'hero.subtitle': 'Your path to Germany starts here in Urgench. Professional German courses from A1 to C2.',
    'hero.cta': 'Discover Courses',
    'hero.feature1': 'Goethe Exam Center',
    'hero.feature1.sub': 'Official exams conducted here',
    'hero.feature2': 'Modern Equipment',
    'hero.feature2.sub': 'Technology, materials & modern classrooms',
    'hero.feature3': 'Qualified Teachers',
    'hero.feature3.sub': 'Latest methods following Goethe standards',
    'hero.feature4': 'Intensive Courses',
    'hero.feature4.sub': '5 days a week for maximum success',
    'hero.contactBtn': 'Contact Us',

    // Courses
    'courses.title': 'Our Courses',
    'courses.subtitle': 'Your path to Germany starts here',
    'courses.germanA1C2': 'German A1-C2',
    'courses.germanA1C2.desc': 'All levels from A1 to C2. Classes 5 days a week – intensity for your maximum success.',
    'courses.ausbildung': 'Studies and Apprenticeship',
    'courses.ausbildung.desc': 'Preparation and placement for studies, apprenticeship and work in Germany',
    'courses.testdaf': 'TestDaF Preparation',
    'courses.testdaf.desc': 'Intensive preparation for studying in Germany',
    'courses.kids': 'Kids Courses',
    'courses.kids.desc': 'Learning German through play for children',
    'courses.level': 'All Levels',
    'courses.duration': 'Weekly',
    'courses.cta.learn': 'Learn More',
    'courses.cta.contact': 'Inquire',

    // About
    'about.hero.line1': 'Our',
    'about.hero.line2': 'Philosophy',
    'about.hero.quote': 'Berliner Language School – not just language lessons, but your first and most reliable step to Germany.',
    'about.overlay.title': 'In Urgench',
    'about.overlay.text': 'We bring German language quality to the heart of Khorezm.',
    'about.why.title': 'Nima uchun Berliner?',
    'about.card.intensity': 'Intensive Courses',
    'about.card.intensity.text': 'Highest quality standards and 5 days a week intensive learning for maximum success.',
    'about.card.goethe.status': 'Official Exam Center',
    'about.card.goethe.status.text': 'Take your Goethe exams directly at our school – no long journeys required.',
    'about.card.global': 'Global Standard',
    'about.card.global.text': 'Our teaching is based on international Goethe Institute methods. With us, there are results.',
    'about.card.teachers': 'Highly Qualified Teachers',
    'about.card.teachers.text': 'Our teachers regularly complete advanced training according to Goethe Institute standards.',
    'about.card.help': 'Learning with Fun',
    'about.card.help.text': 'Learning German is never boring with us – games, interactive materials and creative methods.',
    'about.why.global.title': 'Global Standard',
    'about.why.global.text': 'Our teaching is based on international Goethe Institute methods. With us, there\'s no "just learning", there are results.',
    'about.why.teachers.title': 'Experienced Teachers',
    'about.why.teachers.text': 'Our teachers know not only the language but have experienced German culture and visa processes firsthand.',
    'about.why.help.title': 'Real Help',
    'about.why.help.text': 'We don\'t just teach, we help our students prepare for visa interviews and find their place in Germany.',
    'about.callout.line1': 'Your success is',
    'about.callout.line2': 'our',
    'about.callout.accent': 'main goal',
    'about.callout.quote': 'We use the latest technologies to make every lesson exciting and useful.',
    'about.callout.cta': 'Get in Touch',
    'about.values.title.line1': 'Our',
    'about.values.title.line2': 'Values',
    'about.values.1.title': 'Quality First',
    'about.values.1.text': 'We work with proven Goethe Institute methods and guarantee the highest teaching quality for your success.',
    'about.values.2.title': 'German Atmosphere',
    'about.values.2.text': 'Feel like you\'re on the streets of Berlin while you\'re in Urgench.',

    // Ausbildung Page
    'ausbildung.title': 'Studies, Apprenticeship and Work in Germany',
    'ausbildung.subtitle': 'Your complete guide from Urgench to Germany',
    'ausbildung.process.title': 'How it works',
    'ausbildung.process.step1.title': 'Language Preparation',
    'ausbildung.process.step1.desc': 'Intensive German courses from A1 to B2/C1 to meet language requirements.',
    'ausbildung.process.step2.title': 'Consultation & Orientation',
    'ausbildung.process.step2.desc': 'We help you find the right studies or apprenticeship in Germany.',
    'ausbildung.process.step3.title': 'Application Service',
    'ausbildung.process.step3.desc': 'Professional support in creating resumes and motivation letters.',
    'ausbildung.process.step4.title': 'Visa & Integration',
    'ausbildung.process.step4.desc': 'Guidance through the visa process and preparation for life in Germany.',
    'ausbildung.help.title': 'Consultation and Application Help',
    'ausbildung.help.desc': 'Beyond language elements, we support you with all bureaucracy and application processes with German employers and universities.',

    // Studium Page
    'studium.badge': 'Your Path to Germany',
    'studium.hero.title': 'Studies, Apprenticeship & Work',
    'studium.hero.accent': 'in Germany',
    'studium.hero.subtitle': 'We accompany you from your first German lesson to your start in Germany. Professional consultation and support for your success.',
    'studium.hero.cta': 'Get Consultation',
    'studium.pathways.title': 'Choose Your Path',
    'studium.pathways.subtitle': 'Three paths lead to Germany – we support you on each one',
    'studium.pathway.studium.title': 'Studies',
    'studium.pathway.studium.desc': 'Bachelor\'s and Master\'s programs at German universities',
    'studium.pathway.studium.feature1': 'University application help',
    'studium.pathway.studium.feature2': 'Language courses up to C2',
    'studium.pathway.studium.feature3': 'Visa support',
    'studium.pathway.ausbildung.title': 'Apprenticeship',
    'studium.pathway.ausbildung.desc': 'Dual vocational training with salary at German companies',
    'studium.pathway.ausbildung.feature1': 'Employer placement',
    'studium.pathway.ausbildung.feature2': 'Interview preparation',
    'studium.pathway.ausbildung.feature3': 'Support until contract',
    'studium.pathway.arbeit.title': 'Skilled Worker',
    'studium.pathway.arbeit.desc': 'Working as a skilled professional with recognized qualifications in Germany',
    'studium.pathway.arbeit.feature1': 'Qualification recognition',
    'studium.pathway.arbeit.feature2': 'Job placement',
    'studium.pathway.arbeit.feature3': 'Integration help',
    'studium.process.title': 'The Path to Germany',
    'studium.process.subtitle': 'Reach your goal in four steps',
    'studium.step1.title': 'Learn German',
    'studium.step1.desc': 'Intensive courses from A1 to the required level',
    'studium.step2.title': 'Prepare Documents',
    'studium.step2.desc': 'We help with resumes, motivation letters and applications',
    'studium.step3.title': 'Consultation & Placement',
    'studium.step3.desc': 'Personal consultation and contact with universities/employers',
    'studium.step4.title': 'Visa & Start',
    'studium.step4.desc': 'Visa support and preparation for life in Germany',
    'studium.benefits.title': 'Why With Us?',
    'studium.benefits.subtitle': 'Over 500 successful graduates are already in Germany – become part of this success story.',
    'studium.benefit1.title': 'Free Education',
    'studium.benefit1.desc': 'German universities charge no tuition fees',
    'studium.benefit2.title': 'Recognized Degrees',
    'studium.benefit2.desc': 'German qualifications valued worldwide',
    'studium.benefit3.title': 'Paid Training',
    'studium.benefit3.desc': 'Earn money during your apprenticeship',
    'studium.benefit4.title': 'High Quality of Life',
    'studium.benefit4.desc': 'Safety, healthcare and career opportunities',
    'studium.benefits.cta': 'Free Consultation',
    'studium.stats.students': 'Graduates',
    'studium.stats.success': 'Success Rate',
    'studium.stats.years': 'Years Experience',
    'studium.cta.title': 'Ready for Your Path to Germany?',
    'studium.cta.subtitle': 'Schedule a free consultation today and take the first step.',
    'studium.cta.button': 'Book Appointment',

    // Contact
    'contact.hero.title': 'Your Questions',
    'contact.hero.accent': 'answered with pleasure',
    'contact.hero.subtitle': 'Learn more about our courses, prices and opportunities to go to Germany. Simply write to us or visit us.',
    'contact.course.a1c2.badge': 'German Courses A1-C2',
    'contact.course.a1c2.title': 'Interested in German Courses?',
    'contact.course.a1c2.desc': 'Contact us for information on current schedules, prices and available spots. We\'re happy to advise you!',
    'contact.course.testdaf.badge': 'TestDaF Preparation',
    'contact.course.testdaf.title': 'TestDaF Exam Preparation',
    'contact.course.testdaf.desc': 'Learn about our TestDaF preparation courses, exam dates and how we prepare you for the exam.',
    'contact.course.kids.badge': 'Kids Courses',
    'contact.course.kids.title': 'German for Children',
    'contact.course.kids.desc': 'Ask about our playful children\'s courses, age groups, times and prices.',
    'contact.course.studium.badge': 'Studies & Apprenticeship',
    'contact.course.studium.title': 'Path to Germany',
    'contact.course.studium.desc': 'Get advice on studies, apprenticeship or work in Germany. We help you at every step.',
    'contact.phone.label': 'Call Us',
    'contact.telegram.label': 'Quick Response',
    'contact.telegram.title': 'Write to us on Telegram',
    'contact.instagram.label': 'Our Daily Life',
    'contact.address': 'Address',
    'contact.hours.label': 'Opening Hours',
    'contact.hours.days': 'Monday — Saturday',

    // Footer
    'footer.rights': 'All rights reserved',
    'footer.tagline': 'Your German language school in Urgench',
    'footer.social': 'Social Networks',

    // Testimonials
    'testimonials.title': 'Student Reviews',
    'testimonials.subtitle': 'Find out what our students say about us',

    // Header utility
    'header.search': 'Search',
    'header.search.placeholder': 'Search...',
    'header.myBerliner': 'My Berliner',
    'header.login': 'Log In',
    'header.register': 'Register',

    // News
    'news.title': 'News',
    'news.subtitle': 'Latest news from our language school',
    'news.readMore': 'Read More',
    'city.name': 'Urgench',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function detectBrowserLanguage(): Language {
  const stored = localStorage.getItem('preferred-language');
  if (stored && ['de', 'ru', 'uz', 'en'].includes(stored)) {
    return stored as Language;
  }

  const browserLang = navigator.language.toLowerCase();

  if (browserLang.startsWith('uz')) return 'uz';
  if (browserLang.startsWith('ru')) return 'ru';
  if (browserLang.startsWith('de')) return 'de';
  if (browserLang.startsWith('en')) return 'en';

  return 'uz'; // Default to Uzbek
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => detectBrowserLanguage());

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('preferred-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
