import { createContext, useContext, useState, type ReactNode } from 'react';

export type Language = 'de' | 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.courses': 'Kurse',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.mission': 'Unsere Mission',
    'nav.ausbildung': 'Ausbildung & Arbeit',

    // Hero
    'hero.title': 'Lernen Sie Deutsch mit Leidenschaft',
    'hero.subtitle': 'Ihr Weg nach Deutschland beginnt hier - bei "Berliner" in Urganch. Professionelle Deutschkurse von A1 bis C2.',
    'hero.cta': 'Kurse entdecken',

    // Courses
    'courses.title': 'Unsere Kurse',
    'courses.subtitle': 'Ihr Weg nach Deutschland beginnt hier - bei "Berliner"',
    'courses.germanA1C2': 'Deutsch A1-C2',
    'courses.germanA1C2.desc': 'Alle Niveaustufen von Anfänger bis Experte',
    'courses.ausbildung': 'Ausbildung & Arbeit',
    'courses.ausbildung.desc': 'Vorbereitung und Vermittlung für Ausbildung und Arbeit in Deutschland',
    'courses.testdaf': 'TestDaF Vorbereitung',
    'courses.testdaf.desc': 'Intensive Vorbereitung fürs Studium in Deutschland',
    'courses.kids': 'Kinderkurse',
    'courses.kids.desc': 'Spielerisch Deutsch lernen für Kinder',
    'courses.level': 'Alle Niveaus',
    'courses.duration': 'Wöchentlich',

    // About
    'about.title': 'Über Sprachschule Berliner',
    'about.text1': 'In Urganch sind wir Ihr Partner für erstklassigen Deutschunterricht. Unsere erfahrenen Lehrer bringen Ihnen nicht nur die Sprache bei, sondern auch die deutsche Kultur.',
    'about.text2': 'Wir bieten kleine Gruppen, flexible Kurszeiten und moderne Lehrmethoden für Ihren optimalen Lernerfolg auf dem Weg nach Deutschland.',
    'about.students': 'Zufriedene Schüler',
    'about.experience': 'Jahre Erfahrung',
    'about.teachers': 'Qualifizierte Lehrer',
    'about.feature1': 'Professionelle Muttersprachler',
    'about.feature2': 'Kleine Gruppenklassen',
    'about.feature3': 'Flexible Terminplanung',
    'about.feature4': 'Moderne Lehrmethoden',

    // About - Team
    'about.team.badge': 'Unser Team',
    'about.team.title': 'Lernen Sie unser Team kennen',
    'about.team.subtitle': 'Erfahrene und engagierte Lehrkräfte für Ihren Erfolg',
    'about.team.member1.name': 'Direktor/in',
    'about.team.member1.role': 'Schulleitung',
    'about.team.member2.name': 'Deutschlehrer/in',
    'about.team.member2.role': 'Senior Dozent',
    'about.team.member3.name': 'Deutschlehrer/in',
    'about.team.member3.role': 'Dozent A1-B2',
    'about.team.member4.name': 'Berater/in',
    'about.team.member4.role': 'Ausbildungsberatung',

    // About - History
    'about.history.badge': 'Unsere Geschichte',
    'about.history.title': 'Die Geschichte von Berliner',
    'about.history.subtitle': 'Von einer Vision zur führenden Sprachschule in Urganch',
    'about.history.2010': 'Gründung der Sprachschule Berliner mit 3 Lehrern und 20 Schülern',
    'about.history.2015': 'Erweiterung auf 200+ Schüler und Einführung von Ausbildungsberatung',
    'about.history.2018': 'Partnerschaft mit deutschen Unternehmen für Arbeitsvermittlung',
    'about.history.2023': 'Über 500 erfolgreiche Absolventen, die jetzt in Deutschland leben',

    // About - Achievements
    'about.achievements.badge': 'Unsere Erfolge',
    'about.achievements.title': 'Erfolge von Berliner',
    'about.achievements.subtitle': 'Wir sind stolz auf das, was wir gemeinsam erreicht haben',
    'about.achievement1.title': '500+ Absolventen',
    'about.achievement1.desc': 'Erfolgreiche Schüler, die jetzt in Deutschland leben und arbeiten',
    'about.achievement2.title': '98% Erfolgsquote',
    'about.achievement2.desc': 'Unsere Schüler bestehen ihre Sprachprüfungen beim ersten Versuch',
    'about.achievement3.title': '50+ Partner',
    'about.achievement3.desc': 'Zusammenarbeit mit deutschen Unternehmen und Bildungseinrichtungen',
    'about.achievement4.title': '15 Jahre Erfahrung',
    'about.achievement4.desc': 'Langjährige Expertise im Deutschunterricht und Beratung',

    // Mission
    'mission.badge': 'Unsere Mission',
    'mission.title': 'Unsere Mission & Vision',
    'mission.subtitle': 'Wir glauben an die Kraft der Bildung, Träume zu verwirklichen und Brücken zwischen Kulturen zu bauen.',
    'mission.statement': 'Wir ermöglichen Menschen aus Usbekistan ihren Traum von Deutschland zu verwirklichen durch erstklassige Sprachausbildung und umfassende Beratung.',
    'mission.vision.title': 'Unsere Vision',
    'mission.vision.text1': 'Wir streben danach, die führende Brücke zwischen Usbekistan und Deutschland zu sein – nicht nur durch Sprachunterricht, sondern durch ganzheitliche Begleitung auf dem Weg in ein neues Leben.',
    'mission.vision.text2': 'Jeder Schüler, der unsere Schule verlässt, soll nicht nur die Sprache beherrschen, sondern auch kulturell auf Deutschland vorbereitet sein.',
    'mission.values.title': 'Unsere Werte',
    'mission.values.subtitle': 'Diese Grundsätze leiten unser tägliches Handeln',
    'mission.value1.title': 'Leidenschaft',
    'mission.value1.desc': 'Wir lieben was wir tun und teilen diese Begeisterung mit unseren Schülern',
    'mission.value2.title': 'Weltoffenheit',
    'mission.value2.desc': 'Wir fördern interkulturelles Verständnis und globales Denken',
    'mission.value3.title': 'Innovation',
    'mission.value3.desc': 'Moderne Lehrmethoden und kontinuierliche Weiterentwicklung',
    'mission.value4.title': 'Gemeinschaft',
    'mission.value4.desc': 'Eine starke Gemeinschaft von Lernenden und Lehrenden',
    'mission.value5.title': 'Exzellenz',
    'mission.value5.desc': 'Höchste Standards in Unterricht und Beratung',
    'mission.value6.title': 'Zielorientierung',
    'mission.value6.desc': 'Fokus auf Ihre persönlichen Ziele und Erfolge',

    // Ausbildung
    'ausbildung.badge': 'Ausbildung & Arbeit',
    'ausbildung.title': 'Ihr Weg zur Ausbildung und Arbeit in Deutschland',
    'ausbildung.subtitle': 'Wir begleiten Sie von der Sprachausbildung bis zum erfolgreichen Start in Deutschland – mit umfassender Beratung und Unterstützung.',
    'ausbildung.cta': 'Kostenlose Beratung anfragen',
    'ausbildung.what.title': 'Was ist eine Ausbildung?',
    'ausbildung.what.text1': 'Die duale Ausbildung in Deutschland kombiniert praktische Arbeit im Betrieb mit theoretischem Unterricht in der Berufsschule. Sie ist weltweit bekannt für ihre Qualität.',
    'ausbildung.what.text2': 'Als Auszubildender erhalten Sie eine Vergütung, lernen einen Beruf von Grund auf und haben ausgezeichnete Karriereaussichten in Deutschland.',
    'ausbildung.duration': '2-3,5 Jahre Ausbildung',
    'ausbildung.salary': '800-1200€ monatlich',
    'ausbildung.process.title': 'Wie läuft der Prozess ab?',
    'ausbildung.process.subtitle': 'Von der ersten Beratung bis zum Arbeitsstart in Deutschland',
    'ausbildung.step1.title': 'Beratung',
    'ausbildung.step1.desc': 'Kostenlose Erstberatung zu Ihren Möglichkeiten',
    'ausbildung.step2.title': 'Sprachkurs',
    'ausbildung.step2.desc': 'Deutsch lernen bis zum benötigten Niveau',
    'ausbildung.step3.title': 'Bewerbung',
    'ausbildung.step3.desc': 'Gemeinsame Erstellung Ihrer Bewerbungsunterlagen',
    'ausbildung.step4.title': 'Vermittlung',
    'ausbildung.step4.desc': 'Vermittlung an deutsche Unternehmen',
    'ausbildung.step5.title': 'Visum & Start',
    'ausbildung.step5.desc': 'Unterstützung bei Visum und Ankunft',
    'ausbildung.services.title': 'Unsere Leistungen',
    'ausbildung.services.subtitle': 'Umfassende Unterstützung auf Ihrem Weg nach Deutschland',
    'ausbildung.service1.title': 'Ausbildungsberatung',
    'ausbildung.service1.desc': 'Individuelle Beratung zu passenden Ausbildungsberufen und Anforderungen',
    'ausbildung.service1.item1': 'Berufsberatung und Eignungstest',
    'ausbildung.service1.item2': 'Informationen zu Branchen und Chancen',
    'ausbildung.service1.item3': 'Anforderungsanalyse für Wunschberufe',
    'ausbildung.service2.title': 'Arbeitsvermittlung',
    'ausbildung.service2.desc': 'Direkter Kontakt zu deutschen Arbeitgebern und Ausbildungsbetrieben',
    'ausbildung.service2.item1': 'Netzwerk von 50+ Partnerunternehmen',
    'ausbildung.service2.item2': 'Stellenvermittlung und Vorauswahl',
    'ausbildung.service2.item3': 'Interviewvorbereitung',
    'ausbildung.service3.title': 'Bewerbungshilfe',
    'ausbildung.service3.desc': 'Professionelle Unterstützung bei allen Bewerbungsunterlagen',
    'ausbildung.service3.item1': 'Lebenslauf nach deutschem Standard',
    'ausbildung.service3.item2': 'Anschreiben und Motivationsschreiben',
    'ausbildung.service3.item3': 'Zeugnisübersetzung und -anerkennung',
    'ausbildung.service4.title': 'Betreuung',
    'ausbildung.service4.desc': 'Kontinuierliche Unterstützung auch nach Ihrer Ankunft',
    'ausbildung.service4.item1': 'Hilfe bei Visumsantrag',
    'ausbildung.service4.item2': 'Unterstützung bei Wohnungssuche',
    'ausbildung.service4.item3': 'Ansprechpartner bei Fragen',
    'ausbildung.benefits.title': 'Warum Ausbildung in Deutschland?',
    'ausbildung.benefit1': 'Weltweit anerkannte Qualifikation',
    'ausbildung.benefit2': 'Bezahlte Ausbildung mit Vergütung',
    'ausbildung.benefit3': 'Hohe Übernahmechancen',
    'ausbildung.benefit4': 'Weg zur Aufenthaltserlaubnis',
    'ausbildung.benefit5': 'Deutsches Berufsbildungssystem',
    'ausbildung.benefit6': 'Karrieremöglichkeiten in der EU',
    'ausbildung.benefits.cta.text': 'Bereit für Ihren Weg nach Deutschland? Kontaktieren Sie uns für eine kostenlose Beratung.',
    'ausbildung.benefits.cta.button': 'Jetzt Beratung anfragen',

    // Contact
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Wir freuen uns auf Ihre Nachricht',
    'contact.name': 'Name',
    'contact.email': 'E-Mail',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht senden',
    'contact.address': 'Adresse',
    'contact.phone': 'Telefon',

    // Footer
    'footer.rights': 'Alle Rechte vorbehalten',
    'footer.tagline': 'Ihre Deutschsprachschule in Urganch',
    'footer.social': 'Soziale Netzwerke',

    // Testimonials
    'testimonials.title': 'Bewertungen unserer Schüler',
    'testimonials.subtitle': 'Erfahren Sie, was unsere Schüler über uns sagen',

    // Header utility
    'header.search': 'Suche',
    'header.search.placeholder': 'Suche...',
    'header.myBerliner': 'Mein Berliner',
    'header.login': 'Anmelden',
    'header.register': 'Registrieren',

    // News
    'news.title': 'Neuigkeiten',
    'news.subtitle': 'Aktuelle Nachrichten aus unserer Sprachschule',
    'news.readMore': 'Weiterlesen',
    'city.name': 'Urgentsch',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.courses': 'Курсы',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.mission': 'Наша миссия',
    'nav.ausbildung': 'Аусбильдунг и работа',

    // Hero
    'hero.title': 'Изучайте немецкий с увлечением',
    'hero.subtitle': 'Ваш путь в Германию начинается здесь - в "Berliner", в Ургенче. Профессиональные курсы немецкого от A1 до C2.',
    'hero.cta': 'Наши курсы',

    // Courses
    'courses.title': 'Наши курсы',
    'courses.subtitle': 'Ваш путь в Германию начинается здесь - в "Berliner"',
    'courses.germanA1C2': 'Немецкий A1-C2',
    'courses.germanA1C2.desc': 'Все уровни от начинающего до эксперта',
    'courses.ausbildung': 'Аусбильдунг и работа',
    'courses.ausbildung.desc': 'Подготовка и помощь в поиске обучения и работы в Германии',
    'courses.testdaf': 'Подготовка к TestDaF',
    'courses.testdaf.desc': 'Интенсивная подготовка к учёбе в Германии',
    'courses.kids': 'Детские курсы',
    'courses.kids.desc': 'Немецкий для детей в игровой форме',
    'courses.level': 'Все уровни',
    'courses.duration': 'Еженедельно',

    // About
    'about.title': 'О школе Sprachschule Berliner',
    'about.text1': 'В Ургенче мы являемся вашим партнером в области первоклассного обучения немецкому языку. Наши опытные преподаватели обучат вас не только языку, но и немецкой культуре.',
    'about.text2': 'Мы предлагаем небольшие группы, гибкое расписание и современные методы обучения для вашего успешного пути в Германию.',
    'about.students': 'Довольных учеников',
    'about.experience': 'Лет опыта',
    'about.teachers': 'Квалифицированных преподавателей',
    'about.feature1': 'Профессиональные носители языка',
    'about.feature2': 'Небольшие группы',
    'about.feature3': 'Гибкое расписание',
    'about.feature4': 'Современные методы обучения',

    // About - Team
    'about.team.badge': 'Наша команда',
    'about.team.title': 'Познакомьтесь с нашей командой',
    'about.team.subtitle': 'Опытные и преданные преподаватели для вашего успеха',
    'about.team.member1.name': 'Директор',
    'about.team.member1.role': 'Руководство школы',
    'about.team.member2.name': 'Преподаватель немецкого',
    'about.team.member2.role': 'Старший преподаватель',
    'about.team.member3.name': 'Преподаватель немецкого',
    'about.team.member3.role': 'Преподаватель A1-B2',
    'about.team.member4.name': 'Консультант',
    'about.team.member4.role': 'Консультация по аусбильдунгу',

    // About - History
    'about.history.badge': 'Наша история',
    'about.history.title': 'История Berliner',
    'about.history.subtitle': 'От идеи до ведущей языковой школы в Ургенче',
    'about.history.2010': 'Основание языковой школы Berliner с 3 преподавателями и 20 учениками',
    'about.history.2015': 'Расширение до 200+ учеников и введение консультаций по аусбильдунгу',
    'about.history.2018': 'Партнерство с немецкими компаниями для трудоустройства',
    'about.history.2023': 'Более 500 успешных выпускников, которые сейчас живут в Германии',

    // About - Achievements
    'about.achievements.badge': 'Наши достижения',
    'about.achievements.title': 'Достижения Berliner',
    'about.achievements.subtitle': 'Мы гордимся тем, чего достигли вместе',
    'about.achievement1.title': '500+ выпускников',
    'about.achievement1.desc': 'Успешные ученики, которые сейчас живут и работают в Германии',
    'about.achievement2.title': '98% успешность',
    'about.achievement2.desc': 'Наши ученики сдают языковые экзамены с первой попытки',
    'about.achievement3.title': '50+ партнеров',
    'about.achievement3.desc': 'Сотрудничество с немецкими компаниями и образовательными учреждениями',
    'about.achievement4.title': '15 лет опыта',
    'about.achievement4.desc': 'Многолетний опыт в преподавании немецкого и консультировании',

    // Mission
    'mission.badge': 'Наша миссия',
    'mission.title': 'Наша миссия и видение',
    'mission.subtitle': 'Мы верим в силу образования для осуществления мечты и построения мостов между культурами.',
    'mission.statement': 'Мы помогаем людям из Узбекистана осуществить их мечту о Германии через первоклассное языковое образование и комплексные консультации.',
    'mission.vision.title': 'Наше видение',
    'mission.vision.text1': 'Мы стремимся стать ведущим мостом между Узбекистаном и Германией – не только через языковое обучение, но и через всестороннее сопровождение на пути к новой жизни.',
    'mission.vision.text2': 'Каждый ученик, покидающий нашу школу, должен не только владеть языком, но и быть культурно подготовленным к жизни в Германии.',
    'mission.values.title': 'Наши ценности',
    'mission.values.subtitle': 'Эти принципы направляют наши ежедневные действия',
    'mission.value1.title': 'Увлеченность',
    'mission.value1.desc': 'Мы любим то, что делаем, и делимся этим энтузиазмом с учениками',
    'mission.value2.title': 'Открытость миру',
    'mission.value2.desc': 'Мы развиваем межкультурное понимание и глобальное мышление',
    'mission.value3.title': 'Инновации',
    'mission.value3.desc': 'Современные методы обучения и постоянное развитие',
    'mission.value4.title': 'Сообщество',
    'mission.value4.desc': 'Крепкое сообщество учеников и преподавателей',
    'mission.value5.title': 'Превосходство',
    'mission.value5.desc': 'Высочайшие стандарты в обучении и консультировании',
    'mission.value6.title': 'Целеустремленность',
    'mission.value6.desc': 'Фокус на ваших личных целях и успехах',

    // Ausbildung
    'ausbildung.badge': 'Аусбильдунг и работа',
    'ausbildung.title': 'Ваш путь к аусбильдунгу и работе в Германии',
    'ausbildung.subtitle': 'Мы сопровождаем вас от языкового обучения до успешного старта в Германии – с полной консультацией и поддержкой.',
    'ausbildung.cta': 'Запросить бесплатную консультацию',
    'ausbildung.what.title': 'Что такое аусбильдунг?',
    'ausbildung.what.text1': 'Дуальное обучение в Германии сочетает практическую работу на предприятии с теоретическим обучением в профессиональной школе. Оно известно во всем мире своим качеством.',
    'ausbildung.what.text2': 'Как ученик вы получаете зарплату, изучаете профессию с нуля и имеете отличные карьерные перспективы в Германии.',
    'ausbildung.duration': '2-3,5 года обучения',
    'ausbildung.salary': '800-1200€ в месяц',
    'ausbildung.process.title': 'Как проходит процесс?',
    'ausbildung.process.subtitle': 'От первой консультации до начала работы в Германии',
    'ausbildung.step1.title': 'Консультация',
    'ausbildung.step1.desc': 'Бесплатная первичная консультация о ваших возможностях',
    'ausbildung.step2.title': 'Языковой курс',
    'ausbildung.step2.desc': 'Изучение немецкого до нужного уровня',
    'ausbildung.step3.title': 'Заявка',
    'ausbildung.step3.desc': 'Совместная подготовка ваших документов',
    'ausbildung.step4.title': 'Трудоустройство',
    'ausbildung.step4.desc': 'Подбор немецких компаний',
    'ausbildung.step5.title': 'Виза и старт',
    'ausbildung.step5.desc': 'Помощь с визой и прибытием',
    'ausbildung.services.title': 'Наши услуги',
    'ausbildung.services.subtitle': 'Комплексная поддержка на вашем пути в Германию',
    'ausbildung.service1.title': 'Консультация по аусбильдунгу',
    'ausbildung.service1.desc': 'Индивидуальная консультация по подходящим профессиям и требованиям',
    'ausbildung.service1.item1': 'Профориентация и тест на пригодность',
    'ausbildung.service1.item2': 'Информация об отраслях и возможностях',
    'ausbildung.service1.item3': 'Анализ требований для желаемой профессии',
    'ausbildung.service2.title': 'Трудоустройство',
    'ausbildung.service2.desc': 'Прямой контакт с немецкими работодателями и учебными предприятиями',
    'ausbildung.service2.item1': 'Сеть из 50+ партнерских компаний',
    'ausbildung.service2.item2': 'Подбор вакансий и предварительный отбор',
    'ausbildung.service2.item3': 'Подготовка к собеседованию',
    'ausbildung.service3.title': 'Помощь с заявками',
    'ausbildung.service3.desc': 'Профессиональная помощь со всеми документами',
    'ausbildung.service3.item1': 'Резюме по немецкому стандарту',
    'ausbildung.service3.item2': 'Сопроводительное и мотивационное письмо',
    'ausbildung.service3.item3': 'Перевод и признание документов',
    'ausbildung.service4.title': 'Сопровождение',
    'ausbildung.service4.desc': 'Постоянная поддержка даже после вашего прибытия',
    'ausbildung.service4.item1': 'Помощь с визовой заявкой',
    'ausbildung.service4.item2': 'Помощь с поиском жилья',
    'ausbildung.service4.item3': 'Контактное лицо для вопросов',
    'ausbildung.benefits.title': 'Почему аусбильдунг в Германии?',
    'ausbildung.benefit1': 'Всемирно признанная квалификация',
    'ausbildung.benefit2': 'Оплачиваемое обучение с зарплатой',
    'ausbildung.benefit3': 'Высокие шансы на трудоустройство',
    'ausbildung.benefit4': 'Путь к виду на жительство',
    'ausbildung.benefit5': 'Немецкая система профобразования',
    'ausbildung.benefit6': 'Карьерные возможности в ЕС',
    'ausbildung.benefits.cta.text': 'Готовы к вашему пути в Германию? Свяжитесь с нами для бесплатной консультации.',
    'ausbildung.benefits.cta.button': 'Запросить консультацию',

    // Contact
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Мы будем рады вашему сообщению',
    'contact.name': 'Имя',
    'contact.email': 'Эл. почта',
    'contact.message': 'Сообщение',
    'contact.send': 'Отправить сообщение',
    'contact.address': 'Адрес',
    'contact.phone': 'Телефон',

    // Footer
    'footer.rights': 'Все права защищены',
    'footer.tagline': 'Ваша школа немецкого языка в Ургенче',
    'footer.social': 'Социальные сети',

    // Testimonials
    'testimonials.title': 'Отзывы наших учеников',
    'testimonials.subtitle': 'Узнайте, что говорят о нас наши ученики',

    // Header utility
    'header.search': 'Поиск',
    'header.search.placeholder': 'Поиск...',
    'header.myBerliner': 'Мой Берлинер',
    'header.login': 'Войти',
    'header.register': 'Регистрация',

    // News
    'news.title': 'Новости',
    'news.subtitle': 'Актуальные новости из нашей языковой школы',
    'news.readMore': 'Читать далее',
    'city.name': 'Ургенч',
  },
  uz: {
    // Navigation
    'nav.home': 'Bosh sahifa',
    'nav.courses': 'Kurslar',
    'nav.about': 'Biz haqimizda',
    'nav.contact': 'Aloqa',
    'nav.mission': 'Bizning missiya',
    'nav.ausbildung': 'Ausbildung va ish',

    // Hero
    'hero.title': "Nemis tilini ishtiyoq bilan o'rganing",
    'hero.subtitle': 'Germaniyaga yo\'lingiz shu yerda - "Berliner"da boshlanadi. A1 dan C2 gacha professional nemis tili kurslari.',
    'hero.cta': 'Kurslarimiz bilan tanishing',

    // Courses
    'courses.title': 'Bizning kurslar',
    'courses.subtitle': 'Germaniyaga yo\'lingiz shu yerda - "Berliner"da boshlanadi',
    'courses.germanA1C2': 'Nemis tili A1-C2',
    'courses.germanA1C2.desc': "Boshlang'ichdan ekspertgacha barcha darajalar",
    'courses.ausbildung': 'Ausbildung va ish',
    'courses.ausbildung.desc': "Germaniyada ta'lim va ish topishga tayyorgarlik va yordam",
    'courses.testdaf': 'TestDaF tayyorgarlik',
    'courses.testdaf.desc': "Germaniyada o'qish uchun intensiv tayyorgarlik",
    'courses.kids': 'Bolalar kurslari',
    'courses.kids.desc': "Bolalar uchun o'yin orqali nemis tili",
    'courses.level': 'Barcha darajalar',
    'courses.duration': 'Haftalik',

    // About
    'about.title': 'Sprachschule Berliner haqida',
    'about.text1': "Urganchda biz sizning nemis tilini o'rganishdagi ishonchli hamkoringizmiz. Tajribali o'qituvchilarimiz sizga nafaqat tilni, balki nemis madaniyatini ham o'rgatadi.",
    'about.text2': "Biz kichik guruhlar, moslashuvchan dars jadvali va Germaniyaga muvaffaqiyatli yo'lingiz uchun zamonaviy o'qitish usullarini taklif etamiz.",
    'about.students': "Mamnun o'quvchilar",
    'about.experience': 'Yillik tajriba',
    'about.teachers': "Malakali o'qituvchilar",
    'about.feature1': "Professional ona tili o'qituvchilari",
    'about.feature2': 'Kichik guruhlar',
    'about.feature3': 'Moslashuvchan jadval',
    'about.feature4': "Zamonaviy o'qitish usullari",

    // About - Team, History, Achievements
    'about.team.badge': 'Bizning jamoa',
    'about.team.title': 'Jamoamiz bilan tanishing',
    'about.team.subtitle': "Sizning muvaffaqiyatingiz uchun tajribali va fidoyi o'qituvchilar",
    'about.team.member1.name': 'Direktor',
    'about.team.member1.role': "Maktab rahbariyati",
    'about.team.member2.name': "Nemis tili o'qituvchisi",
    'about.team.member2.role': "Katta o'qituvchi",
    'about.team.member3.name': "Nemis tili o'qituvchisi",
    'about.team.member3.role': "A1-B2 o'qituvchi",
    'about.team.member4.name': 'Maslahatchi',
    'about.team.member4.role': 'Ausbildung maslahati',
    'about.history.badge': 'Bizning tarix',
    'about.history.title': 'Berliner tarixi',
    'about.history.subtitle': "G'oyadan Urganchdagi yetakchi til maktabigacha",
    'about.history.2010': "Berliner til maktabining 3 o'qituvchi va 20 o'quvchi bilan tashkil etilishi",
    'about.history.2015': "200+ o'quvchiga kengayish va Ausbildung maslahati joriy etilishi",
    'about.history.2018': "Ishga joylashtirish uchun nemis kompaniyalari bilan hamkorlik",
    'about.history.2023': "Germaniyada yashovchi 500+ muvaffaqiyatli bitiruvchilar",
    'about.achievements.badge': 'Bizning yutuqlar',
    'about.achievements.title': 'Berliner yutuqlari',
    'about.achievements.subtitle': "Biz birga erishgan narsalarimiz bilan faxrlanamiz",
    'about.achievement1.title': '500+ bitiruvchilar',
    'about.achievement1.desc': "Hozir Germaniyada yashab, ishlab kelayotgan muvaffaqiyatli o'quvchilar",
    'about.achievement2.title': '98% muvaffaqiyat',
    'about.achievement2.desc': "O'quvchilarimiz til imtihonlarini birinchi urinishda topshiradi",
    'about.achievement3.title': '50+ hamkorlar',
    'about.achievement3.desc': "Nemis kompaniyalari va ta'lim muassasalari bilan hamkorlik",
    'about.achievement4.title': '15 yillik tajriba',
    'about.achievement4.desc': "Nemis tilini o'qitish va maslahat berishda ko'p yillik tajriba",

    // Mission & Ausbildung (simplified for brevity)
    'mission.badge': 'Bizning missiya',
    'mission.title': 'Bizning missiya va qarashlarimiz',
    'mission.subtitle': "Biz ta'lim kuchiga ishonamiz - orzularni amalga oshirish va madaniyatlar o'rtasida ko'prik qurish.",
    'mission.statement': "Biz O'zbekiston fuqarolariga yuqori sifatli til ta'limi va keng qamrovli maslahat orqali Germaniya orzusini amalga oshirishga yordam beramiz.",
    'mission.vision.title': 'Bizning qarashimiz',
    'mission.vision.text1': "Biz O'zbekiston va Germaniya o'rtasida yetakchi ko'prik bo'lishga intilamiz.",
    'mission.vision.text2': "Maktabimizni tark etgan har bir o'quvchi nafaqat tilni, balki madaniy jihatdan ham Germaniyaga tayyor bo'lishi kerak.",
    'mission.values.title': 'Bizning qadriyatlarimiz',
    'mission.values.subtitle': "Bu tamoyillar kundalik harakatlarimizni boshqaradi",
    'mission.value1.title': 'Ishtiyoq',
    'mission.value1.desc': "Biz ishimizni sevamiz va bu zavqni o'quvchilarimiz bilan baham ko'ramiz",
    'mission.value2.title': 'Dunyo ochilganlik',
    'mission.value2.desc': "Biz madaniyatlararo tushunish va global fikrlashni rivojlantiramiz",
    'mission.value3.title': 'Innovatsiya',
    'mission.value3.desc': "Zamonaviy o'qitish usullari va doimiy rivojlanish",
    'mission.value4.title': 'Jamoa',
    'mission.value4.desc': "O'quvchilar va o'qituvchilarning kuchli jamoasi",
    'mission.value5.title': 'Mukammallik',
    'mission.value5.desc': "O'qitish va maslahatlashda eng yuqori standartlar",
    'mission.value6.title': "Maqsadga yo'nalish",
    'mission.value6.desc': 'Sizning shaxsiy maqsadlaringiz va muvaffaqiyatlaringizga e\'tibor',

    // Ausbildung
    'ausbildung.badge': 'Ausbildung va ish',
    'ausbildung.title': "Germaniyada Ausbildung va ishga yo'lingiz",
    'ausbildung.subtitle': "Biz sizni til o'rganishdan Germaniyada muvaffaqiyatli boshlanishgacha - to'liq maslahat va qo'llab-quvvatlash bilan kuzatamiz.",
    'ausbildung.cta': "Bepul maslahat so'rash",
    'ausbildung.what.title': 'Ausbildung nima?',
    'ausbildung.what.text1': "Germaniyadagi dual ta'lim korxonada amaliy ish va kasb-hunar maktabida nazariy ta'limni birlashtiradi.",
    'ausbildung.what.text2': "O'quvchi sifatida siz maosh olasiz, kasbni boshidan o'rganasiz va Germaniyada ajoyib karyera imkoniyatlariga ega bo'lasiz.",
    'ausbildung.duration': "2-3,5 yillik ta'lim",
    'ausbildung.salary': 'Oyiga 800-1200€',
    'ausbildung.process.title': 'Jarayon qanday kechadi?',
    'ausbildung.process.subtitle': "Birinchi maslahatdan Germaniyada ish boshlashgacha",
    'ausbildung.step1.title': 'Maslahat',
    'ausbildung.step1.desc': "Imkoniyatlaringiz haqida bepul dastlabki maslahat",
    'ausbildung.step2.title': 'Til kursi',
    'ausbildung.step2.desc': "Kerakli darajagacha nemis tilini o'rganish",
    'ausbildung.step3.title': 'Ariza',
    'ausbildung.step3.desc': 'Hujjatlaringizni birgalikda tayyorlash',
    'ausbildung.step4.title': 'Ish topish',
    'ausbildung.step4.desc': 'Nemis kompaniyalariga joylashtirish',
    'ausbildung.step5.title': 'Viza va boshlash',
    'ausbildung.step5.desc': 'Viza va kelish bilan yordam',
    'ausbildung.services.title': 'Bizning xizmatlar',
    'ausbildung.services.subtitle': "Germaniyaga yo'lingizda keng qamrovli qo'llab-quvvatlash",
    'ausbildung.service1.title': 'Ausbildung maslahati',
    'ausbildung.service1.desc': "Mos kasblar va talablar bo'yicha individual maslahat",
    'ausbildung.service1.item1': "Kasb-hunar maslahati va yaroqlilik testi",
    'ausbildung.service1.item2': "Sohalar va imkoniyatlar haqida ma'lumot",
    'ausbildung.service1.item3': "Xohish kasblari uchun talablar tahlili",
    'ausbildung.service2.title': 'Ish topish',
    'ausbildung.service2.desc': "Nemis ish beruvchilari va ta'lim korxonalari bilan to'g'ridan-to'g'ri aloqa",
    'ausbildung.service2.item1': "50+ hamkor kompaniyalar tarmog'i",
    'ausbildung.service2.item2': "Vakansiyalarni joylashtirish va oldindan tanlash",
    'ausbildung.service2.item3': 'Suhbatga tayyorgarlik',
    'ausbildung.service3.title': 'Ariza yordami',
    'ausbildung.service3.desc': "Barcha hujjatlar bo'yicha professional yordam",
    'ausbildung.service3.item1': "Nemis standartiga mos rezyume",
    'ausbildung.service3.item2': "Hamroh va motivatsion xat",
    'ausbildung.service3.item3': "Hujjatlarni tarjima va tan olish",
    'ausbildung.service4.title': 'Kuzatuv',
    'ausbildung.service4.desc': "Kelganingizdan keyin ham doimiy qo'llab-quvvatlash",
    'ausbildung.service4.item1': "Viza arizasi bilan yordam",
    'ausbildung.service4.item2': "Uy-joy topishda yordam",
    'ausbildung.service4.item3': "Savollar uchun aloqa shaxsi",
    'ausbildung.benefits.title': 'Nima uchun Germaniyada Ausbildung?',
    'ausbildung.benefit1': 'Dunyo miqyosida tan olingan malaka',
    'ausbildung.benefit2': "Maosh bilan to'lanadigan ta'lim",
    'ausbildung.benefit3': 'Yuqori ishga joylashish imkoniyati',
    'ausbildung.benefit4': "Yashash ruxsatnomasiga yo'l",
    'ausbildung.benefit5': "Nemis kasb-hunar ta'limi tizimi",
    'ausbildung.benefit6': "YIda karyera imkoniyatlari",
    'ausbildung.benefits.cta.text': "Germaniyaga yo'lingizga tayyormisiz? Bepul maslahat uchun biz bilan bog'laning.",
    'ausbildung.benefits.cta.button': "Hozir maslahat so'rash",

    // Contact, Footer, etc.
    'contact.title': 'Biz bilan bog\'laning',
    'contact.subtitle': "Xabaringizni kutib qolamiz",
    'contact.name': 'Ism',
    'contact.email': 'Elektron pochta',
    'contact.message': 'Xabar',
    'contact.send': 'Xabar yuborish',
    'contact.address': 'Manzil',
    'contact.phone': 'Telefon',
    'footer.rights': "Barcha huquqlar himoyalangan",
    'footer.tagline': 'Urganchdagi nemis tili maktabingiz',
    'footer.social': 'Ijtimoiy tarmoqlar',
    'testimonials.title': "O'quvchilarimiz fikrlari",
    'testimonials.subtitle': "O'quvchilarimiz biz haqimizda nima deyishlarini bilib oling",
    'header.search': 'Qidiruv',
    'header.search.placeholder': 'Qidirish...',
    'header.myBerliner': 'Mening Berliner',
    'header.login': 'Kirish',
    'header.register': "Ro'yxatdan o'tish",
    'news.title': 'Yangiliklar',
    'news.subtitle': "Til maktabimizdan so'nggi yangiliklar",
    'news.readMore': "Ko'proq o'qish",
    'city.name': 'Urganch',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('uz');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
